### ISSUE TITLE
Use for server-side validation

### ISSUE THREAD

**Issue by elitenoire** [gitjs/redux-form-with-ajv#5]
How do I process the request I get from client redux-form on node express server?
Since import is not supported on node , I try to require the module but I get error saying it is not a function.

**Comment by adam187** [comment]
@elitenoire This library is wrapper on https://github.com/epoberezkin/ajv for easier integration with https://github.com/erikras/redux-form on frontend side. If you want to do request validation on server side you should probably use https://github.com/epoberezkin/ajv itself.

If you want to import it in node.js you need to do it like this:

```javascript
var validate = require("redux-form-with-ajv").default;
```
because it's not using commonJS module style export.

**Comment by gitjs** [comment]
You can of course use babel-node, included by babel-cli package, to run node with es6 syntax. This is not a problem at all. 

But i don't understand your question so well, to give a proper answer.

As adam mentioned and i fully agree with him, this package can be used in frontend. There it doesn't matter which kind of technique you use, whether client-side or server-side rendering.

**Comment by elitenoire** [comment]
Thanks @adam187 your method to import worked as desired.

Yes, i'm using ajv on server-side, it's error reporting that i was looking into, because this package formats errors in the style suitable for redux-form
